---
title: "conaway_hw6_r"
output: word_document
---

Homework 6
Kelsey Conaway
Stat 5193
11/1/18

R-Markdown, won't see arrows


```{r}

```


Question 1
```{r}
texts<-StudentData$TxtRec-StudentData$TxtSent
txt<-texts[-28]
int<-StudentData$Introvert[-28]
plot(int,txt,
     xlab="Introversion Level",
     ylab="Texts Received-Texts Sent",
     xlim=c(1,8),
     ylim=c(-20,101))

title(sub="Scale: 1-10", cex.sub=0.8)
title(main="Texting vs. Introversion", cex.main=2.0, font.main=4, col.main="red")

points(StudentData$Introvert[28],StudentData$TxtRec[28]-StudentData$TxtSent[28],pch="X",col="green")
text(x=StudentData$Introvert[28], y=StudentData$TxtRec[28]-StudentData$TxtSent[28],labels="Outlier",pos=4)

abline(h=0,col="blue",lty=2)
```

Question 2
```{r}
plot(int,txt,
     xlab="Introversion Level",
     ylab="Texts Received-Texts Sent",
     xlim=c(1,8),
     ylim=c(-25,20))

title(sub="Scale: 1-10", cex.sub=0.8)
title(main="Outlier Analysis", cex.main=2.0, font.main=4, col.main="red")

outlier_reg<-lm(StudentData$TxtRec-StudentData$TxtSent~StudentData$Introvert)
no_outlier_reg<-lm(txt~int)

lines(abline(outlier_reg, col="red",lwd=3))
lines(abline(no_outlier_reg, col="black",lwd=3,lty=2))
abline(h=0,col="blue",lty=2)

legend("bottomleft",
       inset=0.05,
       title="Fits",
       c("With Outlier","Without Outlier"),
       col=c("red","black"),
       lty=c(1,2))
```

Question 3
```{r}
plot(int,txt,
     xlab="Introversion Level",
     ylab="Texts Received-Texts Sent",
     xlim=c(1,8),
     ylim=c(-25,20),
     pch = c(1,2)[as.numeric(as.factor(StudentData$Snapchat))],
     col=c("black","red")[as.numeric(as.factor(StudentData$Snapchat))])
    


title(sub="Scale: 1-10", cex.sub=0.8)
title(main="Texting vs. Introversion vs. Snapchat",
      cex.main=2.0,
      font.main=4, 
      col.main="red")

```
