---
title: "Midterm"
author: "Kelsey Conaway"
date: "November 15, 2018"
output: pdf_document
---
STAT 5193

Question 1 - c
```{r}
rm(list=ls())
ls()
```

Question 2
```{r}
KMC<-read.table(file="clipboard",header=T)
rownames(KMC)<-c(1:35)
```

Question 3
```{r}
KMC[c(3,5),]
```
Question 4
```{r}
KMC_order<-KMC[order(KMC$Gender,KMC$Introvert),]
KMC_order[1:3,]
```

Question 5
```{r}
KMC$HSClass.cat[KMC$HSClass<=100]<-"Small"
KMC$HSClass.cat[KMC$HSClass>100]<-"Large"
summary(KMC$HSClass.cat)
```

Question 6
```{r}
KMC_HSclass_factor<-factor(
                      KMC$HSClass.cat,
                      order=T,
                      levels=c("Small","Large"))

summary(KMC_HSclass_factor)
```

Question 7
```{r}
Texts<-matrix(c(KMC$TxtSent,KMC$TxtRec),nrow=35)
summary(Texts)
```

Question 8-10 c
```{r}
plot(KMC$TxtSent~KMC$TxtRec, 
     xlab="Texts Received",
     ylab="Texts Sent",
     col=c("pink","blue")[KMC$Gender])
#Question 9
text(x=KMC$TxtRec[18],
     y=KMC$TextSent[18],
     labels="He's Popular?",
     pos=4)

#Question 10
title(main="Texting vs. Gender",col.main="blue")

#Question 11
legend("bottomright",
  inset=0.05,
  c("Female","Male"),
  col=c("pink","blue"),
  pch=c("F","M"))

#Question 12
male<-KMC_order[24:35,]
female<-KMC_order[1:23,]
lines(abline(lm(male$TxtSent~male$TxtRec)), col="blue")
lines(abline(lm(female$TxtSent~female$TxtRec)), col="pink")
```

Question 13
```{r}
binomial<-rbinom(1000,50,0.5)
hist(binomial,probability = T)
curve(dnorm(x,mean=25,sd=sqrt(12.5)),add=T)
```

Question 14

of.age<-function(name,age=21)
  {
  x<-"is"
  if( )
  {
    x<-"is not"
  }
  ouput <- paste(name,is,x,21)
  return()
}

Question 15
my.sampled.data<- vector("double",length=10000)

}
make a vector 1000 in length
loop 1:1000 samples into the vector where replace=f

vector<-vector("double",length=10000)
for(i in 1:10000)
{
vector[i]<-


  
  













